FROM node:22-bookworm-slim

USER root

RUN mkdir -p /tmp/yo-home \
  && chmod -R 777 /tmp/yo-home

ENV HOME=/tmp/yo-home

WORKDIR /workspace

COPY .generator /opt/codegen/.generator

RUN cd /opt/codegen/.generator && npm ci --omit=dev

COPY gen.sh /usr/local/bin/gen
COPY update-codegen-model.js /usr/local/bin/update
RUN ln -s /usr/local/bin/update /usr/local/bin/update-codegen-model \
  && ln -s /usr/local/bin/update /usr/local/bin/fetch-codegen-model \
  && chmod +x /usr/local/bin/gen /usr/local/bin/update

CMD ["/bin/bash"]
