server:
  port: ${SERVER_PORT:<%= appPort %>}

spring:
  application:
    name: <%= appName %>
  docker:
    compose:
      file: ${DOCKER_COMPOSE_FILE:<%= composeFile %>}
      lifecycle-management: start-and-stop
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:<%= dbPort %>/<%= dbName %>}
    username: ${DB_USERNAME:medol}
    password: ${DB_PASSWORD:medol}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration

axon:
  axonserver:
    enabled: false
  eventstorage:
    jpa:
      batch-size: 100
      gap-cleaning-threshold: 250
      gap-timeout: 10000
      lowest-global-sequence: 1
      max-gap-offset: 60000
      polling-interval: 1000

medol:
  axon:
    event-storage-mode: dcb

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
